// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _AddCheckInEp } from '../src/api/addCheckIn';
import type { default as _AddCommentEp } from '../src/api/addComment';
import type { default as _AiBreakdownIssueEp } from '../src/api/aiBreakdownIssue';
import type { default as _AiDraftCheckInEp } from '../src/api/aiDraftCheckIn';
import type { default as _AiDraftIssueEp } from '../src/api/aiDraftIssue';
import type { default as _AiFindDuplicatesEp } from '../src/api/aiFindDuplicates';
import type { default as _AiSprintRiskEp } from '../src/api/aiSprintRisk';
import type { default as _AiSummarizeThreadEp } from '../src/api/aiSummarizeThread';
import type { default as _BootstrapEp } from '../src/api/bootstrap';
import type { default as _BulkUpdateIssuesEp } from '../src/api/bulkUpdateIssues';
import type { default as _CompleteSprintEp } from '../src/api/completeSprint';
import type { default as _CreateIssueEp } from '../src/api/createIssue';
import type { default as _DeleteIssuesEp } from '../src/api/deleteIssues';
import type { default as _GetAnalyticsEp } from '../src/api/getAnalytics';
import type { default as _GetIssueEp } from '../src/api/getIssue';
import type { default as _GetProjectEp } from '../src/api/getProject';
import type { default as _GetSprintEp } from '../src/api/getSprint';
import type { default as _ListIssuesEp } from '../src/api/listIssues';
import type { default as _ListNotificationsEp } from '../src/api/listNotifications';
import type { default as _ListProjectsEp } from '../src/api/listProjects';
import type { default as _ListSprintsEp } from '../src/api/listSprints';
import type { default as _MoveIssueEp } from '../src/api/moveIssue';
import type { default as _SaveAttachmentEp } from '../src/api/saveAttachment';
import type { default as _SaveGoalEp } from '../src/api/saveGoal';
import type { default as _SaveLabelEp } from '../src/api/saveLabel';
import type { default as _SaveMemberEp } from '../src/api/saveMember';
import type { default as _SaveMilestoneEp } from '../src/api/saveMilestone';
import type { default as _SaveProjectEp } from '../src/api/saveProject';
import type { default as _SaveSprintEp } from '../src/api/saveSprint';
import type { default as _SaveStatusEp } from '../src/api/saveStatus';
import type { default as _SaveTeamEp } from '../src/api/saveTeam';
import type { default as _SaveTemplateEp } from '../src/api/saveTemplate';
import type { default as _SaveViewEp } from '../src/api/saveView';
import type { default as _SearchEp } from '../src/api/search';
import type { default as _SeedWorkspaceEp } from '../src/api/seedWorkspace';
import type { default as _SendDueRemindersEp } from '../src/api/sendDueReminders';
import type { default as _SetIssueLabelsEp } from '../src/api/setIssueLabels';
import type { default as _SetIssueRelationEp } from '../src/api/setIssueRelation';
import type { default as _TogglePinEp } from '../src/api/togglePin';
import type { default as _ToggleReactionEp } from '../src/api/toggleReaction';
import type { default as _ToggleSubscriptionEp } from '../src/api/toggleSubscription';
import type { default as _UpdateCommentEp } from '../src/api/updateComment';
import type { default as _UpdateIssueEp } from '../src/api/updateIssue';
import type { default as _UpdateNotificationsEp } from '../src/api/updateNotifications';

type _AddCheckInCfg = typeof _AddCheckInEp;
export type AddCheckInInputType = NonNullable<_AddCheckInCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AddCheckInCfg['execute']>[0]['input'];
export type AddCheckInOutputType = Awaited<ReturnType<_AddCheckInCfg['execute']>>;
export const addCheckIn = createCaller<AddCheckInInputType, AddCheckInOutputType>('addCheckIn');

type _AddCommentCfg = typeof _AddCommentEp;
export type AddCommentInputType = NonNullable<_AddCommentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AddCommentCfg['execute']>[0]['input'];
export type AddCommentOutputType = Awaited<ReturnType<_AddCommentCfg['execute']>>;
export const addComment = createCaller<AddCommentInputType, AddCommentOutputType>('addComment');

type _AiBreakdownIssueCfg = typeof _AiBreakdownIssueEp;
export type AiBreakdownIssueInputType = NonNullable<_AiBreakdownIssueCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiBreakdownIssueCfg['execute']>[0]['input'];
export type AiBreakdownIssueOutputType = Awaited<ReturnType<_AiBreakdownIssueCfg['execute']>>;
export const aiBreakdownIssue = createCaller<AiBreakdownIssueInputType, AiBreakdownIssueOutputType>('aiBreakdownIssue');

type _AiDraftCheckInCfg = typeof _AiDraftCheckInEp;
export type AiDraftCheckInInputType = NonNullable<_AiDraftCheckInCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiDraftCheckInCfg['execute']>[0]['input'];
export type AiDraftCheckInOutputType = Awaited<ReturnType<_AiDraftCheckInCfg['execute']>>;
export const aiDraftCheckIn = createCaller<AiDraftCheckInInputType, AiDraftCheckInOutputType>('aiDraftCheckIn');

type _AiDraftIssueCfg = typeof _AiDraftIssueEp;
export type AiDraftIssueInputType = NonNullable<_AiDraftIssueCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiDraftIssueCfg['execute']>[0]['input'];
export type AiDraftIssueOutputType = Awaited<ReturnType<_AiDraftIssueCfg['execute']>>;
export const aiDraftIssue = createCaller<AiDraftIssueInputType, AiDraftIssueOutputType>('aiDraftIssue');

type _AiFindDuplicatesCfg = typeof _AiFindDuplicatesEp;
export type AiFindDuplicatesInputType = NonNullable<_AiFindDuplicatesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiFindDuplicatesCfg['execute']>[0]['input'];
export type AiFindDuplicatesOutputType = Awaited<ReturnType<_AiFindDuplicatesCfg['execute']>>;
export const aiFindDuplicates = createCaller<AiFindDuplicatesInputType, AiFindDuplicatesOutputType>('aiFindDuplicates');

type _AiSprintRiskCfg = typeof _AiSprintRiskEp;
export type AiSprintRiskInputType = NonNullable<_AiSprintRiskCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiSprintRiskCfg['execute']>[0]['input'];
export type AiSprintRiskOutputType = Awaited<ReturnType<_AiSprintRiskCfg['execute']>>;
export const aiSprintRisk = createCaller<AiSprintRiskInputType, AiSprintRiskOutputType>('aiSprintRisk');

type _AiSummarizeThreadCfg = typeof _AiSummarizeThreadEp;
export type AiSummarizeThreadInputType = NonNullable<_AiSummarizeThreadCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiSummarizeThreadCfg['execute']>[0]['input'];
export type AiSummarizeThreadOutputType = Awaited<ReturnType<_AiSummarizeThreadCfg['execute']>>;
export const aiSummarizeThread = createCaller<AiSummarizeThreadInputType, AiSummarizeThreadOutputType>('aiSummarizeThread');

type _BootstrapCfg = typeof _BootstrapEp;
export type BootstrapInputType = NonNullable<_BootstrapCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_BootstrapCfg['execute']>[0]['input'];
export type BootstrapOutputType = Awaited<ReturnType<_BootstrapCfg['execute']>>;
export const bootstrap = createCaller<BootstrapInputType, BootstrapOutputType>('bootstrap');

type _BulkUpdateIssuesCfg = typeof _BulkUpdateIssuesEp;
export type BulkUpdateIssuesInputType = NonNullable<_BulkUpdateIssuesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_BulkUpdateIssuesCfg['execute']>[0]['input'];
export type BulkUpdateIssuesOutputType = Awaited<ReturnType<_BulkUpdateIssuesCfg['execute']>>;
export const bulkUpdateIssues = createCaller<BulkUpdateIssuesInputType, BulkUpdateIssuesOutputType>('bulkUpdateIssues');

type _CompleteSprintCfg = typeof _CompleteSprintEp;
export type CompleteSprintInputType = NonNullable<_CompleteSprintCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CompleteSprintCfg['execute']>[0]['input'];
export type CompleteSprintOutputType = Awaited<ReturnType<_CompleteSprintCfg['execute']>>;
export const completeSprint = createCaller<CompleteSprintInputType, CompleteSprintOutputType>('completeSprint');

type _CreateIssueCfg = typeof _CreateIssueEp;
export type CreateIssueInputType = NonNullable<_CreateIssueCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateIssueCfg['execute']>[0]['input'];
export type CreateIssueOutputType = Awaited<ReturnType<_CreateIssueCfg['execute']>>;
export const createIssue = createCaller<CreateIssueInputType, CreateIssueOutputType>('createIssue');

type _DeleteIssuesCfg = typeof _DeleteIssuesEp;
export type DeleteIssuesInputType = NonNullable<_DeleteIssuesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteIssuesCfg['execute']>[0]['input'];
export type DeleteIssuesOutputType = Awaited<ReturnType<_DeleteIssuesCfg['execute']>>;
export const deleteIssues = createCaller<DeleteIssuesInputType, DeleteIssuesOutputType>('deleteIssues');

type _GetAnalyticsCfg = typeof _GetAnalyticsEp;
export type GetAnalyticsInputType = NonNullable<_GetAnalyticsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetAnalyticsCfg['execute']>[0]['input'];
export type GetAnalyticsOutputType = Awaited<ReturnType<_GetAnalyticsCfg['execute']>>;
export const getAnalytics = createCaller<GetAnalyticsInputType, GetAnalyticsOutputType>('getAnalytics');

type _GetIssueCfg = typeof _GetIssueEp;
export type GetIssueInputType = NonNullable<_GetIssueCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetIssueCfg['execute']>[0]['input'];
export type GetIssueOutputType = Awaited<ReturnType<_GetIssueCfg['execute']>>;
export const getIssue = createCaller<GetIssueInputType, GetIssueOutputType>('getIssue');

type _GetProjectCfg = typeof _GetProjectEp;
export type GetProjectInputType = NonNullable<_GetProjectCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetProjectCfg['execute']>[0]['input'];
export type GetProjectOutputType = Awaited<ReturnType<_GetProjectCfg['execute']>>;
export const getProject = createCaller<GetProjectInputType, GetProjectOutputType>('getProject');

type _GetSprintCfg = typeof _GetSprintEp;
export type GetSprintInputType = NonNullable<_GetSprintCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetSprintCfg['execute']>[0]['input'];
export type GetSprintOutputType = Awaited<ReturnType<_GetSprintCfg['execute']>>;
export const getSprint = createCaller<GetSprintInputType, GetSprintOutputType>('getSprint');

type _ListIssuesCfg = typeof _ListIssuesEp;
export type ListIssuesInputType = NonNullable<_ListIssuesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListIssuesCfg['execute']>[0]['input'];
export type ListIssuesOutputType = Awaited<ReturnType<_ListIssuesCfg['execute']>>;
export const listIssues = createCaller<ListIssuesInputType, ListIssuesOutputType>('listIssues');

type _ListNotificationsCfg = typeof _ListNotificationsEp;
export type ListNotificationsInputType = NonNullable<_ListNotificationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListNotificationsCfg['execute']>[0]['input'];
export type ListNotificationsOutputType = Awaited<ReturnType<_ListNotificationsCfg['execute']>>;
export const listNotifications = createCaller<ListNotificationsInputType, ListNotificationsOutputType>('listNotifications');

type _ListProjectsCfg = typeof _ListProjectsEp;
export type ListProjectsInputType = NonNullable<_ListProjectsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListProjectsCfg['execute']>[0]['input'];
export type ListProjectsOutputType = Awaited<ReturnType<_ListProjectsCfg['execute']>>;
export const listProjects = createCaller<ListProjectsInputType, ListProjectsOutputType>('listProjects');

type _ListSprintsCfg = typeof _ListSprintsEp;
export type ListSprintsInputType = NonNullable<_ListSprintsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListSprintsCfg['execute']>[0]['input'];
export type ListSprintsOutputType = Awaited<ReturnType<_ListSprintsCfg['execute']>>;
export const listSprints = createCaller<ListSprintsInputType, ListSprintsOutputType>('listSprints');

type _MoveIssueCfg = typeof _MoveIssueEp;
export type MoveIssueInputType = NonNullable<_MoveIssueCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_MoveIssueCfg['execute']>[0]['input'];
export type MoveIssueOutputType = Awaited<ReturnType<_MoveIssueCfg['execute']>>;
export const moveIssue = createCaller<MoveIssueInputType, MoveIssueOutputType>('moveIssue');

type _SaveAttachmentCfg = typeof _SaveAttachmentEp;
export type SaveAttachmentInputType = NonNullable<_SaveAttachmentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveAttachmentCfg['execute']>[0]['input'];
export type SaveAttachmentOutputType = Awaited<ReturnType<_SaveAttachmentCfg['execute']>>;
export const saveAttachment = createCaller<SaveAttachmentInputType, SaveAttachmentOutputType>('saveAttachment');

type _SaveGoalCfg = typeof _SaveGoalEp;
export type SaveGoalInputType = NonNullable<_SaveGoalCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveGoalCfg['execute']>[0]['input'];
export type SaveGoalOutputType = Awaited<ReturnType<_SaveGoalCfg['execute']>>;
export const saveGoal = createCaller<SaveGoalInputType, SaveGoalOutputType>('saveGoal');

type _SaveLabelCfg = typeof _SaveLabelEp;
export type SaveLabelInputType = NonNullable<_SaveLabelCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveLabelCfg['execute']>[0]['input'];
export type SaveLabelOutputType = Awaited<ReturnType<_SaveLabelCfg['execute']>>;
export const saveLabel = createCaller<SaveLabelInputType, SaveLabelOutputType>('saveLabel');

type _SaveMemberCfg = typeof _SaveMemberEp;
export type SaveMemberInputType = NonNullable<_SaveMemberCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveMemberCfg['execute']>[0]['input'];
export type SaveMemberOutputType = Awaited<ReturnType<_SaveMemberCfg['execute']>>;
export const saveMember = createCaller<SaveMemberInputType, SaveMemberOutputType>('saveMember');

type _SaveMilestoneCfg = typeof _SaveMilestoneEp;
export type SaveMilestoneInputType = NonNullable<_SaveMilestoneCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveMilestoneCfg['execute']>[0]['input'];
export type SaveMilestoneOutputType = Awaited<ReturnType<_SaveMilestoneCfg['execute']>>;
export const saveMilestone = createCaller<SaveMilestoneInputType, SaveMilestoneOutputType>('saveMilestone');

type _SaveProjectCfg = typeof _SaveProjectEp;
export type SaveProjectInputType = NonNullable<_SaveProjectCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveProjectCfg['execute']>[0]['input'];
export type SaveProjectOutputType = Awaited<ReturnType<_SaveProjectCfg['execute']>>;
export const saveProject = createCaller<SaveProjectInputType, SaveProjectOutputType>('saveProject');

type _SaveSprintCfg = typeof _SaveSprintEp;
export type SaveSprintInputType = NonNullable<_SaveSprintCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveSprintCfg['execute']>[0]['input'];
export type SaveSprintOutputType = Awaited<ReturnType<_SaveSprintCfg['execute']>>;
export const saveSprint = createCaller<SaveSprintInputType, SaveSprintOutputType>('saveSprint');

type _SaveStatusCfg = typeof _SaveStatusEp;
export type SaveStatusInputType = NonNullable<_SaveStatusCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveStatusCfg['execute']>[0]['input'];
export type SaveStatusOutputType = Awaited<ReturnType<_SaveStatusCfg['execute']>>;
export const saveStatus = createCaller<SaveStatusInputType, SaveStatusOutputType>('saveStatus');

type _SaveTeamCfg = typeof _SaveTeamEp;
export type SaveTeamInputType = NonNullable<_SaveTeamCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveTeamCfg['execute']>[0]['input'];
export type SaveTeamOutputType = Awaited<ReturnType<_SaveTeamCfg['execute']>>;
export const saveTeam = createCaller<SaveTeamInputType, SaveTeamOutputType>('saveTeam');

type _SaveTemplateCfg = typeof _SaveTemplateEp;
export type SaveTemplateInputType = NonNullable<_SaveTemplateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveTemplateCfg['execute']>[0]['input'];
export type SaveTemplateOutputType = Awaited<ReturnType<_SaveTemplateCfg['execute']>>;
export const saveTemplate = createCaller<SaveTemplateInputType, SaveTemplateOutputType>('saveTemplate');

type _SaveViewCfg = typeof _SaveViewEp;
export type SaveViewInputType = NonNullable<_SaveViewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveViewCfg['execute']>[0]['input'];
export type SaveViewOutputType = Awaited<ReturnType<_SaveViewCfg['execute']>>;
export const saveView = createCaller<SaveViewInputType, SaveViewOutputType>('saveView');

type _SearchCfg = typeof _SearchEp;
export type SearchInputType = NonNullable<_SearchCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SearchCfg['execute']>[0]['input'];
export type SearchOutputType = Awaited<ReturnType<_SearchCfg['execute']>>;
export const search = createCaller<SearchInputType, SearchOutputType>('search');

type _SeedWorkspaceCfg = typeof _SeedWorkspaceEp;
export type SeedWorkspaceInputType = NonNullable<_SeedWorkspaceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SeedWorkspaceCfg['execute']>[0]['input'];
export type SeedWorkspaceOutputType = Awaited<ReturnType<_SeedWorkspaceCfg['execute']>>;
export const seedWorkspace = createCaller<SeedWorkspaceInputType, SeedWorkspaceOutputType>('seedWorkspace');

type _SendDueRemindersCfg = typeof _SendDueRemindersEp;
export type SendDueRemindersInputType = NonNullable<_SendDueRemindersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendDueRemindersCfg['execute']>[0]['input'];
export type SendDueRemindersOutputType = Awaited<ReturnType<_SendDueRemindersCfg['execute']>>;
export const sendDueReminders = createCaller<SendDueRemindersInputType, SendDueRemindersOutputType>('sendDueReminders');

type _SetIssueLabelsCfg = typeof _SetIssueLabelsEp;
export type SetIssueLabelsInputType = NonNullable<_SetIssueLabelsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SetIssueLabelsCfg['execute']>[0]['input'];
export type SetIssueLabelsOutputType = Awaited<ReturnType<_SetIssueLabelsCfg['execute']>>;
export const setIssueLabels = createCaller<SetIssueLabelsInputType, SetIssueLabelsOutputType>('setIssueLabels');

type _SetIssueRelationCfg = typeof _SetIssueRelationEp;
export type SetIssueRelationInputType = NonNullable<_SetIssueRelationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SetIssueRelationCfg['execute']>[0]['input'];
export type SetIssueRelationOutputType = Awaited<ReturnType<_SetIssueRelationCfg['execute']>>;
export const setIssueRelation = createCaller<SetIssueRelationInputType, SetIssueRelationOutputType>('setIssueRelation');

type _TogglePinCfg = typeof _TogglePinEp;
export type TogglePinInputType = NonNullable<_TogglePinCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_TogglePinCfg['execute']>[0]['input'];
export type TogglePinOutputType = Awaited<ReturnType<_TogglePinCfg['execute']>>;
export const togglePin = createCaller<TogglePinInputType, TogglePinOutputType>('togglePin');

type _ToggleReactionCfg = typeof _ToggleReactionEp;
export type ToggleReactionInputType = NonNullable<_ToggleReactionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ToggleReactionCfg['execute']>[0]['input'];
export type ToggleReactionOutputType = Awaited<ReturnType<_ToggleReactionCfg['execute']>>;
export const toggleReaction = createCaller<ToggleReactionInputType, ToggleReactionOutputType>('toggleReaction');

type _ToggleSubscriptionCfg = typeof _ToggleSubscriptionEp;
export type ToggleSubscriptionInputType = NonNullable<_ToggleSubscriptionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ToggleSubscriptionCfg['execute']>[0]['input'];
export type ToggleSubscriptionOutputType = Awaited<ReturnType<_ToggleSubscriptionCfg['execute']>>;
export const toggleSubscription = createCaller<ToggleSubscriptionInputType, ToggleSubscriptionOutputType>('toggleSubscription');

type _UpdateCommentCfg = typeof _UpdateCommentEp;
export type UpdateCommentInputType = NonNullable<_UpdateCommentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateCommentCfg['execute']>[0]['input'];
export type UpdateCommentOutputType = Awaited<ReturnType<_UpdateCommentCfg['execute']>>;
export const updateComment = createCaller<UpdateCommentInputType, UpdateCommentOutputType>('updateComment');

type _UpdateIssueCfg = typeof _UpdateIssueEp;
export type UpdateIssueInputType = NonNullable<_UpdateIssueCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateIssueCfg['execute']>[0]['input'];
export type UpdateIssueOutputType = Awaited<ReturnType<_UpdateIssueCfg['execute']>>;
export const updateIssue = createCaller<UpdateIssueInputType, UpdateIssueOutputType>('updateIssue');

type _UpdateNotificationsCfg = typeof _UpdateNotificationsEp;
export type UpdateNotificationsInputType = NonNullable<_UpdateNotificationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateNotificationsCfg['execute']>[0]['input'];
export type UpdateNotificationsOutputType = Awaited<ReturnType<_UpdateNotificationsCfg['execute']>>;
export const updateNotifications = createCaller<UpdateNotificationsInputType, UpdateNotificationsOutputType>('updateNotifications');


export const api = {
  addCheckIn,
  addComment,
  aiBreakdownIssue,
  aiDraftCheckIn,
  aiDraftIssue,
  aiFindDuplicates,
  aiSprintRisk,
  aiSummarizeThread,
  bootstrap,
  bulkUpdateIssues,
  completeSprint,
  createIssue,
  deleteIssues,
  getAnalytics,
  getIssue,
  getProject,
  getSprint,
  listIssues,
  listNotifications,
  listProjects,
  listSprints,
  moveIssue,
  saveAttachment,
  saveGoal,
  saveLabel,
  saveMember,
  saveMilestone,
  saveProject,
  saveSprint,
  saveStatus,
  saveTeam,
  saveTemplate,
  saveView,
  search,
  seedWorkspace,
  sendDueReminders,
  setIssueLabels,
  setIssueRelation,
  togglePin,
  toggleReaction,
  toggleSubscription,
  updateComment,
  updateIssue,
  updateNotifications,
};
