// Auto-generated by zitejs generate. Do not edit manually.
//
// Usage in endpoint files (src/api/*.ts):
//   import { zite } from "zitejs/db";
//
// Always use "zitejs/db" — never use relative paths like "../../.zite/db".
// The tsconfig aliases resolve zitejs/* imports to the correct .zite/ files.
//
// Table client methods (all take a single params object):
//   .findAll({ filters?, sort?, offset?, limit?, fields? }) → { records: T[], hasMore: boolean }
//     filters: { fieldName: value } for equality, or { fieldName: { <op>: value } }
//     operators: contains, not, in, notIn, lt, lte, gt, gte
//       `not: null` means "is set". An empty `in: []` matches nothing; an
//       empty `notIn: []` applies no filter.
//     sort is currently IGNORED here — it is stripped before the request.
//       (it does work on zite.auth.findAllUsers). Order in SQL instead.
//     limit defaults to 500, max 2000; offset is a row count (a number)
//     a filter value of `undefined` is REJECTED (it would query unfiltered
//       and match an arbitrary record). Check the value first.
//   .findOne({ id?, filters?, fields? }) → T | undefined
//   .create({ record }) → T
//   .update({ id, record }) → { id: string, fields: Partial<T> }
//   .delete({ id }) → { success: true, id: string }
//   .bulkCreate({ records, matchOn? }) → { success: boolean, records: T[] }
//     up to 100 records per call; matchOn upserts on those fields
//
// Reading these types:
//   SDK names are stable identifiers — they do NOT change when a table or field is
//   renamed. Each carries its current user-facing name in quotes (// "Task Name").
//   Where the two differ the field was renamed, and the quoted name is what it means
//   now — treat it as the source of truth.
//   Values are RAW: dates are ISO strings, durations are seconds. Format them for
//   display yourself, following the display config in each field's comment.
//   PERCENT fields are stored as decimals — 0.5 is 50%, 1.0 is 100%.
//   LINKED RECORD fields hold UUID record ids from findOne/findAll — never invent one.
//   Computed and system-managed fields (formula, rollup, lookup, autonumber,
//   created/updated timestamps and more) are absent from the *Input types —
//   a write to one is rejected or silently dropped.
//
// Zite auth users:
//   zite.auth.findAllUsers({ appIds?, filter?, filters?, sort?, limit?, offset? })
//     Supports the same filter, sort, and pagination options as table .findAll()
//     appIds restricts results to users belonging to any listed app
//   zite.auth.updateUserProfile(userId, { firstName?, lastName?, image? })
//   User email addresses cannot be updated through this API
//
// Raw SQL (read-only SELECTs for aggregates, joins, multi-table queries):
//   zite.sql({ query: "SELECT ...", params?: [...] })
//     → { rows: Record<string, unknown>[], columns, rowCount, truncated }
//     Capped at 2000 rows — `truncated: true` means there were more, so paginate in
//     SQL rather than assuming you got everything. Queries time out after 10s.
//     columns[].name is the SDK name; columns[].originalName is the underlying
//     database column (or your own SQL alias).
//
// SQL guidelines:
//   - Use SDK names for tables (PascalCase) and fields (camelCase)
//   - ALWAYS double-quote every identifier: FROM "Orders", WHERE "status" = $1
//   - Use params array for user input ($1, $2, ...): never interpolate into SQL
//   - Auth users are available as "ziteUsers" with id, name, email, firstName, lastName, and image
//   - Soft-deleted rows are excluded automatically — no WHERE deleted_at IS NULL
//   - SELECT only — use .create/.update/.delete for writes
//   - Load the "zite:sql" skill for full SQL reference (formulas, lookups, etc.)
import { createTableClient, createSqlClient, createAuthClient } from 'zitejs/runtime';

/** An attachment as returned when reading a record. */
export type ZiteAttachment = {
  /** Original filename as uploaded. */
  filename: string;
  /** Display name — may differ from `filename`. */
  originalName: string;
  /** File size in bytes. */
  size: number;
  mimeType: string;
  /** Publicly accessible URL. */
  url: string;
  /** ISO timestamp of the upload. */
  uploadedAt: string;
  metadata?: Record<string, unknown>;
};

/** What you may write to an attachments field: a URL, a URL with a name, or an attachment you read earlier. */
export type ZiteAttachmentInput =
  | string
  | { url: string; filename?: string }
  | ZiteAttachment;

/** A record in the "Teams" table, as it is read back. */
export type TeamsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  key?: string;
  description?: string;
  icon?: string;
  color?: string;
  /** "Issue Counter". 0 decimal places, format: local (e.g. 1,000,000.50) */
  issueCounter?: number;
  sprintsEnabled?: boolean;
  /** "Sprint Duration Weeks". 0 decimal places, format: local (e.g. 1,000,000.50) */
  sprintDurationWeeks?: number;
  intakeEnabled?: boolean;
  estimateScale?: "fibonacci" | "linear" | "exponential" | "tshirt" | "none" | string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Teams" table. */
export type TeamsRecordInput = {
  name: string | null;
  key: string | null;
  description: string | null;
  icon: string | null;
  color: string | null;
  issueCounter: string | number | null;
  sprintsEnabled: string | boolean | null;
  sprintDurationWeeks: string | number | null;
  intakeEnabled: string | boolean | null;
  estimateScale: "fibonacci" | "linear" | "exponential" | "tshirt" | "none" | string | null;
  position: string | number | null;
};

/** A record in the "Members" table, as it is read back. */
export type MembersRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  email?: string;
  avatarUrl?: string;
  jobTitle?: string;
  color?: string;
  role?: "Admin" | "Member" | "Guest" | string;
  status?: "Active" | "Invited" | "Deactivated" | string;
};

/** What you may write when creating or updating a record in the "Members" table. */
export type MembersRecordInput = {
  name: string | null;
  email: string | null;
  avatarUrl: string | null;
  jobTitle: string | null;
  color: string | null;
  role: "Admin" | "Member" | "Guest" | string | null;
  status: "Active" | "Invited" | "Deactivated" | string | null;
};

/** A record in the "Team Members" table, as it is read back. */
export type TeamMembersRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  teamId?: string;
  memberId?: string;
};

/** What you may write when creating or updating a record in the "Team Members" table. */
export type TeamMembersRecordInput = {
  name: string | null;
  teamId: string | null;
  memberId: string | null;
};

/** A record in the "Statuses" table, as it is read back. */
export type StatusesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  teamId?: string;
  description?: string;
  color?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
  type?: "intake" | "backlog" | "unstarted" | "started" | "completed" | "canceled" | string;
};

/** What you may write when creating or updating a record in the "Statuses" table. */
export type StatusesRecordInput = {
  name: string | null;
  teamId: string | null;
  description: string | null;
  color: string | null;
  position: string | number | null;
  type: "intake" | "backlog" | "unstarted" | "started" | "completed" | "canceled" | string | null;
};

/** A record in the "Goals" table, as it is read back. */
export type GoalsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  summary?: string;
  description?: string;
  ownerId?: string;
  icon?: string;
  color?: string;
  /** "Target Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  targetDate?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
  status?: "Planned" | "Active" | "Completed" | string;
};

/** What you may write when creating or updating a record in the "Goals" table. */
export type GoalsRecordInput = {
  name: string | null;
  summary: string | null;
  description: string | null;
  ownerId: string | null;
  icon: string | null;
  color: string | null;
  targetDate: string | Date | null;
  position: string | number | null;
  status: "Planned" | "Active" | "Completed" | string | null;
};

/** A record in the "Projects" table, as it is read back. */
export type ProjectsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  summary?: string;
  description?: string;
  leadId?: string;
  teamId?: string;
  goalId?: string;
  icon?: string;
  color?: string;
  /** "Priority". 0 decimal places, format: local (e.g. 1,000,000.50) */
  priority?: number;
  /** "Start Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  startDate?: string;
  /** "Target Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  targetDate?: string;
  /** "Completed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  completedAt?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
  status?: "Backlog" | "Planned" | "In Progress" | "Paused" | "Completed" | "Canceled" | string;
  health?: "On Track" | "At Risk" | "Off Track" | "Unknown" | string;
};

/** What you may write when creating or updating a record in the "Projects" table. */
export type ProjectsRecordInput = {
  name: string | null;
  summary: string | null;
  description: string | null;
  leadId: string | null;
  teamId: string | null;
  goalId: string | null;
  icon: string | null;
  color: string | null;
  priority: string | number | null;
  startDate: string | Date | null;
  targetDate: string | Date | null;
  completedAt: string | Date | null;
  position: string | number | null;
  status: "Backlog" | "Planned" | "In Progress" | "Paused" | "Completed" | "Canceled" | string | null;
  health: "On Track" | "At Risk" | "Off Track" | "Unknown" | string | null;
};

/** A record in the "Milestones" table, as it is read back. */
export type MilestonesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  projectId?: string;
  description?: string;
  /** "Target Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  targetDate?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Milestones" table. */
export type MilestonesRecordInput = {
  name: string | null;
  projectId: string | null;
  description: string | null;
  targetDate: string | Date | null;
  position: string | number | null;
};

/** A record in the "Check Ins" table, as it is read back. */
export type CheckInsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  projectId?: string;
  authorId?: string;
  body?: string;
  health?: "On Track" | "At Risk" | "Off Track" | string;
  /** "Posted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  postedAt?: string;
};

/** What you may write when creating or updating a record in the "Check Ins" table. */
export type CheckInsRecordInput = {
  name: string | null;
  projectId: string | null;
  authorId: string | null;
  body: string | null;
  health: "On Track" | "At Risk" | "Off Track" | string | null;
  postedAt: string | Date | null;
};

/** A record in the "Sprints" table, as it is read back. */
export type SprintsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  /** "Number". 0 decimal places, format: local (e.g. 1,000,000.50) */
  number?: number;
  teamId?: string;
  /** "Start Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  startDate?: string;
  /** "End Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  endDate?: string;
  goal?: string;
  /** "Completed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  completedAt?: string;
};

/** What you may write when creating or updating a record in the "Sprints" table. */
export type SprintsRecordInput = {
  name: string | null;
  number: string | number | null;
  teamId: string | null;
  startDate: string | Date | null;
  endDate: string | Date | null;
  goal: string | null;
  completedAt: string | Date | null;
};

/** A record in the "Issues" table, as it is read back. */
export type IssuesRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  identifier?: string;
  /** "Number". 0 decimal places, format: local (e.g. 1,000,000.50) */
  number?: number;
  teamId?: string;
  description?: string;
  statusId?: string;
  /** "Priority". 0 decimal places, format: local (e.g. 1,000,000.50) */
  priority?: number;
  /** "Estimate". 0 decimal places, format: local (e.g. 1,000,000.50) */
  estimate?: number;
  assigneeId?: string;
  creatorId?: string;
  projectId?: string;
  milestoneId?: string;
  sprintId?: string;
  parentId?: string;
  /** "Due Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  dueDate?: string;
  /** "Started At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  startedAt?: string;
  /** "Completed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  completedAt?: string;
  /** "Canceled At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  canceledAt?: string;
  /** "Opened At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  openedAt?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
  archived?: boolean;
  issueType?: "Feature" | "Bug" | "Improvement" | "Task" | "Spike" | "Chore" | string;
};

/** What you may write when creating or updating a record in the "Issues" table. */
export type IssuesRecordInput = {
  title: string | null;
  identifier: string | null;
  number: string | number | null;
  teamId: string | null;
  description: string | null;
  statusId: string | null;
  priority: string | number | null;
  estimate: string | number | null;
  assigneeId: string | null;
  creatorId: string | null;
  projectId: string | null;
  milestoneId: string | null;
  sprintId: string | null;
  parentId: string | null;
  dueDate: string | Date | null;
  startedAt: string | Date | null;
  completedAt: string | Date | null;
  canceledAt: string | Date | null;
  openedAt: string | Date | null;
  position: string | number | null;
  archived: string | boolean | null;
  issueType: "Feature" | "Bug" | "Improvement" | "Task" | "Spike" | "Chore" | string | null;
};

/** A record in the "Labels" table, as it is read back. */
export type LabelsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  color?: string;
  description?: string;
  teamId?: string;
};

/** What you may write when creating or updating a record in the "Labels" table. */
export type LabelsRecordInput = {
  name: string | null;
  color: string | null;
  description: string | null;
  teamId: string | null;
};

/** A record in the "Issue Labels" table, as it is read back. */
export type IssueLabelsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  issueId?: string;
  labelId?: string;
};

/** What you may write when creating or updating a record in the "Issue Labels" table. */
export type IssueLabelsRecordInput = {
  name: string | null;
  issueId: string | null;
  labelId: string | null;
};

/** A record in the "Comments" table, as it is read back. */
export type CommentsRecordType = {
  id: string;
  /** Primary field. "Body" */
  body?: string;
  issueId?: string;
  authorId?: string;
  parentId?: string;
  /** "Edited At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  editedAt?: string;
  /** "Posted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  postedAt?: string;
  resolved?: boolean;
};

/** What you may write when creating or updating a record in the "Comments" table. */
export type CommentsRecordInput = {
  body: string | null;
  issueId: string | null;
  authorId: string | null;
  parentId: string | null;
  editedAt: string | Date | null;
  postedAt: string | Date | null;
  resolved: string | boolean | null;
};

/** A record in the "Activity" table, as it is read back. */
export type ActivityRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  issueId?: string;
  actorId?: string;
  fromValue?: string;
  toValue?: string;
  fromLabel?: string;
  toLabel?: string;
  type?: "created" | "status_changed" | "assignee_changed" | "priority_changed" | "estimate_changed" | "title_changed" | "description_changed" | "type_changed" | "label_added" | "label_removed" | "project_changed" | "milestone_changed" | "sprint_changed" | "due_date_changed" | "parent_changed" | "relation_added" | "relation_removed" | "attachment_added" | "attachment_removed" | "archived" | "unarchived" | "team_changed" | string;
  /** "Occurred At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  occurredAt?: string;
};

/** What you may write when creating or updating a record in the "Activity" table. */
export type ActivityRecordInput = {
  name: string | null;
  issueId: string | null;
  actorId: string | null;
  fromValue: string | null;
  toValue: string | null;
  fromLabel: string | null;
  toLabel: string | null;
  type: "created" | "status_changed" | "assignee_changed" | "priority_changed" | "estimate_changed" | "title_changed" | "description_changed" | "type_changed" | "label_added" | "label_removed" | "project_changed" | "milestone_changed" | "sprint_changed" | "due_date_changed" | "parent_changed" | "relation_added" | "relation_removed" | "attachment_added" | "attachment_removed" | "archived" | "unarchived" | "team_changed" | string | null;
  occurredAt: string | Date | null;
};

/** A record in the "Issue Relations" table, as it is read back. */
export type IssueRelationsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  issueId?: string;
  relatedIssueId?: string;
  type?: "blocks" | "blocked_by" | "relates" | "duplicate_of" | "duplicated_by" | string;
};

/** What you may write when creating or updating a record in the "Issue Relations" table. */
export type IssueRelationsRecordInput = {
  name: string | null;
  issueId: string | null;
  relatedIssueId: string | null;
  type: "blocks" | "blocked_by" | "relates" | "duplicate_of" | "duplicated_by" | string | null;
};

/** A record in the "Issue Subscribers" table, as it is read back. */
export type IssueSubscribersRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  issueId?: string;
  memberId?: string;
};

/** What you may write when creating or updating a record in the "Issue Subscribers" table. */
export type IssueSubscribersRecordInput = {
  name: string | null;
  issueId: string | null;
  memberId: string | null;
};

/** A record in the "Reactions" table, as it is read back. */
export type ReactionsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  commentId?: string;
  issueId?: string;
  memberId?: string;
  emoji?: string;
};

/** What you may write when creating or updating a record in the "Reactions" table. */
export type ReactionsRecordInput = {
  name: string | null;
  commentId: string | null;
  issueId: string | null;
  memberId: string | null;
  emoji: string | null;
};

/** A record in the "Views" table, as it is read back. */
export type ViewsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  description?: string;
  ownerId?: string;
  teamId?: string;
  icon?: string;
  color?: string;
  filters?: string;
  grouping?: string;
  ordering?: string;
  options?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
  scope?: "Personal" | "Team" | "Workspace" | string;
  display?: "List" | "Board" | "Table" | string;
};

/** What you may write when creating or updating a record in the "Views" table. */
export type ViewsRecordInput = {
  name: string | null;
  description: string | null;
  ownerId: string | null;
  teamId: string | null;
  icon: string | null;
  color: string | null;
  filters: string | null;
  grouping: string | null;
  ordering: string | null;
  options: string | null;
  position: string | number | null;
  scope: "Personal" | "Team" | "Workspace" | string | null;
  display: "List" | "Board" | "Table" | string | null;
};

/** A record in the "Pins" table, as it is read back. */
export type PinsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  memberId?: string;
  entityId?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
  entityType?: "Project" | "View" | "Sprint" | "Issue" | "Team" | "Goal" | string;
};

/** What you may write when creating or updating a record in the "Pins" table. */
export type PinsRecordInput = {
  name: string | null;
  memberId: string | null;
  entityId: string | null;
  position: string | number | null;
  entityType: "Project" | "View" | "Sprint" | "Issue" | "Team" | "Goal" | string | null;
};

/** A record in the "Notifications" table, as it is read back. */
export type NotificationsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  body?: string;
  memberId?: string;
  actorId?: string;
  issueId?: string;
  projectId?: string;
  commentId?: string;
  /** "Read At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  readAt?: string;
  /** "Snoozed Until". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  snoozedUntil?: string;
  read?: boolean;
  archived?: boolean;
  type?: "assigned" | "unassigned" | "mentioned" | "commented" | "status_changed" | "priority_changed" | "completed" | "check_in" | "due_soon" | "blocked" | "subscribed" | "reaction" | "intake" | string;
  /** "Occurred At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  occurredAt?: string;
};

/** What you may write when creating or updating a record in the "Notifications" table. */
export type NotificationsRecordInput = {
  name: string | null;
  body: string | null;
  memberId: string | null;
  actorId: string | null;
  issueId: string | null;
  projectId: string | null;
  commentId: string | null;
  readAt: string | Date | null;
  snoozedUntil: string | Date | null;
  read: string | boolean | null;
  archived: string | boolean | null;
  type: "assigned" | "unassigned" | "mentioned" | "commented" | "status_changed" | "priority_changed" | "completed" | "check_in" | "due_soon" | "blocked" | "subscribed" | "reaction" | "intake" | string | null;
  occurredAt: string | Date | null;
};

/** A record in the "Issue Attachments" table, as it is read back. */
export type IssueAttachmentsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  issueId?: string;
  url?: string;
  creatorId?: string;
  /** "Added At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  addedAt?: string;
  kind?: "link" | "github" | "figma" | "doc" | "loom" | "sentry" | string;
};

/** What you may write when creating or updating a record in the "Issue Attachments" table. */
export type IssueAttachmentsRecordInput = {
  title: string | null;
  issueId: string | null;
  url: string | null;
  creatorId: string | null;
  addedAt: string | Date | null;
  kind: "link" | "github" | "figma" | "doc" | "loom" | "sentry" | string | null;
};

/** A record in the "Issue Templates" table, as it is read back. */
export type IssueTemplatesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  teamId?: string;
  title?: string;
  description?: string;
  /** "Priority". 0 decimal places, format: local (e.g. 1,000,000.50) */
  priority?: number;
  /** "Estimate". 0 decimal places, format: local (e.g. 1,000,000.50) */
  estimate?: number;
  labelIds?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
  issueType?: "Feature" | "Bug" | "Improvement" | "Task" | "Spike" | "Chore" | string;
};

/** What you may write when creating or updating a record in the "Issue Templates" table. */
export type IssueTemplatesRecordInput = {
  name: string | null;
  teamId: string | null;
  title: string | null;
  description: string | null;
  priority: string | number | null;
  estimate: string | number | null;
  labelIds: string | null;
  position: string | number | null;
  issueType: "Feature" | "Bug" | "Improvement" | "Task" | "Spike" | "Chore" | string | null;
};

export interface NotificationLink {
  path?: string;
  params?: Record<string, string>;
}

export interface NotificationsCreateParams {
  recipients: string[];
  title: string;
  body?: string;
  link?: NotificationLink;
  path?: string;
  params?: Record<string, string>;
  payload?: Record<string, unknown>;
  idempotencyKey?: string;
}

export type NotificationsCreateResult =
  | { created: number }
  | { created: 0; preview: true; wouldCreate: number };

export interface ZiteAuthUser {
  id: string;
  name: string;
  email: string;
  firstName?: string;
  lastName?: string;
  image: string | null;
}

export const zite = {
  teams: createTableClient<TeamsRecordType, TeamsRecordInput>('Teams'), // "Teams"
  members: createTableClient<MembersRecordType, MembersRecordInput>('Members'), // "Members"
  teamMembers: createTableClient<TeamMembersRecordType, TeamMembersRecordInput>('TeamMembers'), // "Team Members"
  statuses: createTableClient<StatusesRecordType, StatusesRecordInput>('Statuses'), // "Statuses"
  goals: createTableClient<GoalsRecordType, GoalsRecordInput>('Goals'), // "Goals"
  projects: createTableClient<ProjectsRecordType, ProjectsRecordInput>('Projects'), // "Projects"
  milestones: createTableClient<MilestonesRecordType, MilestonesRecordInput>('Milestones'), // "Milestones"
  checkIns: createTableClient<CheckInsRecordType, CheckInsRecordInput>('CheckIns'), // "Check Ins"
  sprints: createTableClient<SprintsRecordType, SprintsRecordInput>('Sprints'), // "Sprints"
  issues: createTableClient<IssuesRecordType, IssuesRecordInput>('Issues'), // "Issues"
  labels: createTableClient<LabelsRecordType, LabelsRecordInput>('Labels'), // "Labels"
  issueLabels: createTableClient<IssueLabelsRecordType, IssueLabelsRecordInput>('IssueLabels'), // "Issue Labels"
  comments: createTableClient<CommentsRecordType, CommentsRecordInput>('Comments'), // "Comments"
  activity: createTableClient<ActivityRecordType, ActivityRecordInput>('Activity'), // "Activity"
  issueRelations: createTableClient<IssueRelationsRecordType, IssueRelationsRecordInput>('IssueRelations'), // "Issue Relations"
  issueSubscribers: createTableClient<IssueSubscribersRecordType, IssueSubscribersRecordInput>('IssueSubscribers'), // "Issue Subscribers"
  reactions: createTableClient<ReactionsRecordType, ReactionsRecordInput>('Reactions'), // "Reactions"
  views: createTableClient<ViewsRecordType, ViewsRecordInput>('Views'), // "Views"
  pins: createTableClient<PinsRecordType, PinsRecordInput>('Pins'), // "Pins"
  notifications: createTableClient<NotificationsRecordType, NotificationsRecordInput>('Notifications'), // "Notifications"
  issueAttachments: createTableClient<IssueAttachmentsRecordType, IssueAttachmentsRecordInput>('IssueAttachments'), // "Issue Attachments"
  issueTemplates: createTableClient<IssueTemplatesRecordType, IssueTemplatesRecordInput>('IssueTemplates'), // "Issue Templates"
  sql: createSqlClient(),
  auth: createAuthClient<ZiteAuthUser>(),
};
